clientID=50039299089.8ELRSWZEFWCZ1H4LDLH9ZWW09VRVAZ
clientSecret=1a53749d8b36992abfa243b59daa5707ef68d56c5f
JWTClientID=50039299089.VCWJAKK81DF97HPACSVFPVYDU6WP2Z
JWTClientSecret=ad8d6907db10ff092963457c76c1e45265775b054d
notificationAppID={{notificationAppID}}
portalID=50039299089
redirectUrl=deliverysync
projectID=17682000000819069
apiBaseURL=https://api.catalyst.zoho.in
AccountsPortalDomain=https://delivery-sync-60040289923.development.catalystserverless.in
oauthScopes=ZohoCatalyst.zcql.CREATE,ZohoCatalyst.files.READ,ZohoCatalyst.tables.columns.READ,ZohoCatalyst.tables.rows.CREATE,ZohoCatalyst.projects.users.READ,ZohoCatalyst.files.CREATE,ZohoCatalyst.tables.rows.UPDATE,ZohoCatalyst.tables.READ,ZohoCatalyst.cache.READ,ZohoCatalyst.tables.rows.READ,ZohoCatalyst.tables.rows.DELETE,ZohoCatalyst.mltools.READ,ZohoCatalyst.projects.users.CREATE,ZohoCatalyst.functions.execute.CUSTOM,ZohoCatalyst.files.DELETE,ZohoCatalyst.catalyst.search.READ,ZohoCatalyst.folders.READ,ZohoCatalyst.projects.config.READ,Stratus.fileop.ALL,ZohoCatalyst.buckets.objects.ALL,ZohoCatalyst.notifications.mobile.register.CUSTOM,AaaServer.profile.READ
requestHeaders=PROJECT_ID:50039299089,X-Catalyst-Environment:Development,X-CATALYST-USER:user
printStackTrace=true
minLogLevel=ALL
httpRequestMode=ASYNC
connectTimeOutInSec=20
readTimeOutInSec=20
writeTimeOutInSec=20
zcqlParser=V1
StratusDomainSuffix=.zohostratus.in
NimbusDomainSuffix=.nimbuspop.com