'use strict';
const express = require('express');
const router  = express.Router();
const AuthMiddleware     = require('./middleware/AuthMiddleware');
const categoryRoutes     = require('./routes/categoryRoutes');
const inventoryRoutes    = require('./routes/inventoryRoutes');
const requestRoutes      = require('./routes/requestRoutes');
const assignmentRoutes   = require('./routes/assignmentRoutes');
const maintenanceRoutes  = require('./routes/maintenanceRoutes');
const cronRoutes         = require('./routes/cronRoutes');
router.get('/health', (req, res) => res.json({ success: true, service: 'asset_service', ts: Date.now() }));
router.use(AuthMiddleware.authenticate);
router.use('/categories',   categoryRoutes);
router.use('/inventory',    inventoryRoutes);
router.use('/requests',     requestRoutes);
router.use('/assignments',  assignmentRoutes);
router.use('/maintenance',  maintenanceRoutes);
router.use('/cron',         cronRoutes);
module.exports = router;
