'use strict';

// ─── User Roles ───────────────────────────────────────────────────────────────
const ROLES = Object.freeze({
  TENANT_ADMIN: 'TENANT_ADMIN',
  DELIVERY_LEAD: 'DELIVERY_LEAD',
  TEAM_MEMBER: 'TEAM_MEMBER',
  PMO: 'PMO',
  EXEC: 'EXEC',
  CLIENT: 'CLIENT',
});

// ─── Permissions — Full 54-permission set ─────────────────────────────────────
const PERMISSIONS = Object.freeze({
  // Existing
  PROJECT_READ: 'PROJECT_READ', PROJECT_WRITE: 'PROJECT_WRITE',
  STANDUP_SUBMIT: 'STANDUP_SUBMIT', STANDUP_READ: 'STANDUP_READ',
  EOD_SUBMIT: 'EOD_SUBMIT', EOD_READ: 'EOD_READ',
  ACTION_READ: 'ACTION_READ', ACTION_WRITE: 'ACTION_WRITE',
  BLOCKER_READ: 'BLOCKER_READ', BLOCKER_WRITE: 'BLOCKER_WRITE',
  RAID_READ: 'RAID_READ', RAID_WRITE: 'RAID_WRITE',
  DECISION_READ: 'DECISION_READ', DECISION_WRITE: 'DECISION_WRITE',
  MILESTONE_READ: 'MILESTONE_READ', MILESTONE_WRITE: 'MILESTONE_WRITE',
  REPORT_READ: 'REPORT_READ', REPORT_WRITE: 'REPORT_WRITE',
  DASHBOARD_READ: 'DASHBOARD_READ',
  ADMIN_USERS: 'ADMIN_USERS', ADMIN_SETTINGS: 'ADMIN_SETTINGS',
  INVITE_USER: 'INVITE_USER',
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  TEAM_READ: 'TEAM_READ', TEAM_WRITE: 'TEAM_WRITE',
  AI_READ: 'AI_READ',
  AUDIT_READ: 'AUDIT_READ',
  // Tasks & Sprints
  TASK_READ: 'TASK_READ', TASK_WRITE: 'TASK_WRITE',
  TASK_COMMENT_WRITE: 'TASK_COMMENT_WRITE',
  SPRINT_READ: 'SPRINT_READ', SPRINT_WRITE: 'SPRINT_WRITE',
  // Time
  TIME_READ: 'TIME_READ', TIME_WRITE: 'TIME_WRITE', TIME_APPROVE: 'TIME_APPROVE',
  // Attendance
  ATTENDANCE_READ: 'ATTENDANCE_READ', ATTENDANCE_WRITE: 'ATTENDANCE_WRITE', ATTENDANCE_ADMIN: 'ATTENDANCE_ADMIN',
  // Leave
  LEAVE_READ: 'LEAVE_READ', LEAVE_WRITE: 'LEAVE_WRITE', LEAVE_APPROVE: 'LEAVE_APPROVE', LEAVE_ADMIN: 'LEAVE_ADMIN',
  // Assets
  ASSET_READ: 'ASSET_READ', ASSET_WRITE: 'ASSET_WRITE',
  ASSET_ASSIGN: 'ASSET_ASSIGN', ASSET_APPROVE: 'ASSET_APPROVE', ASSET_ADMIN: 'ASSET_ADMIN',
  // Badges & Profile
  BADGE_READ: 'BADGE_READ', BADGE_WRITE: 'BADGE_WRITE', BADGE_AWARD: 'BADGE_AWARD',
  PROFILE_READ: 'PROFILE_READ', PROFILE_WRITE: 'PROFILE_WRITE',
  // Announcements
  ANNOUNCEMENT_READ: 'ANNOUNCEMENT_READ', ANNOUNCEMENT_WRITE: 'ANNOUNCEMENT_WRITE',
  // Org & Config
  ORG_READ: 'ORG_READ', ORG_WRITE: 'ORG_WRITE',
  CONFIG_READ: 'CONFIG_READ', CONFIG_WRITE: 'CONFIG_WRITE',
});

// ─── Role → Permission Matrix ─────────────────────────────────────────────────
const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.TENANT_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.PMO]: [
    PERMISSIONS.PROJECT_READ, PERMISSIONS.PROJECT_WRITE,
    PERMISSIONS.STANDUP_READ, PERMISSIONS.EOD_READ,
    PERMISSIONS.ACTION_READ, PERMISSIONS.ACTION_WRITE,
    PERMISSIONS.BLOCKER_READ, PERMISSIONS.BLOCKER_WRITE,
    PERMISSIONS.RAID_READ, PERMISSIONS.RAID_WRITE,
    PERMISSIONS.DECISION_READ, PERMISSIONS.DECISION_WRITE,
    PERMISSIONS.MILESTONE_READ, PERMISSIONS.MILESTONE_WRITE,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_WRITE,
    PERMISSIONS.DASHBOARD_READ, PERMISSIONS.INVITE_USER,
    PERMISSIONS.NOTIFICATION_READ, PERMISSIONS.TEAM_READ, PERMISSIONS.TEAM_WRITE,
    PERMISSIONS.AI_READ, PERMISSIONS.AUDIT_READ,
    PERMISSIONS.TASK_READ, PERMISSIONS.TASK_WRITE, PERMISSIONS.TASK_COMMENT_WRITE,
    PERMISSIONS.SPRINT_READ, PERMISSIONS.SPRINT_WRITE,
    PERMISSIONS.TIME_READ, PERMISSIONS.TIME_APPROVE,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_ADMIN,
    PERMISSIONS.LEAVE_READ, PERMISSIONS.LEAVE_APPROVE, PERMISSIONS.LEAVE_ADMIN,
    PERMISSIONS.ASSET_READ, PERMISSIONS.ASSET_ASSIGN, PERMISSIONS.ASSET_APPROVE,
    PERMISSIONS.BADGE_READ, PERMISSIONS.BADGE_WRITE, PERMISSIONS.BADGE_AWARD,
    PERMISSIONS.PROFILE_READ, PERMISSIONS.ANNOUNCEMENT_READ, PERMISSIONS.ANNOUNCEMENT_WRITE,
    PERMISSIONS.ORG_READ, PERMISSIONS.ORG_WRITE, PERMISSIONS.CONFIG_READ,
  ],
  [ROLES.DELIVERY_LEAD]: [
    PERMISSIONS.PROJECT_READ, PERMISSIONS.PROJECT_WRITE,
    PERMISSIONS.STANDUP_SUBMIT, PERMISSIONS.STANDUP_READ,
    PERMISSIONS.EOD_SUBMIT, PERMISSIONS.EOD_READ,
    PERMISSIONS.ACTION_READ, PERMISSIONS.ACTION_WRITE,
    PERMISSIONS.BLOCKER_READ, PERMISSIONS.BLOCKER_WRITE,
    PERMISSIONS.RAID_READ, PERMISSIONS.RAID_WRITE,
    PERMISSIONS.DECISION_READ, PERMISSIONS.DECISION_WRITE,
    PERMISSIONS.MILESTONE_READ, PERMISSIONS.MILESTONE_WRITE,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_WRITE,
    PERMISSIONS.DASHBOARD_READ, PERMISSIONS.INVITE_USER,
    PERMISSIONS.NOTIFICATION_READ, PERMISSIONS.TEAM_READ, PERMISSIONS.TEAM_WRITE,
    PERMISSIONS.AI_READ,
    PERMISSIONS.TASK_READ, PERMISSIONS.TASK_WRITE, PERMISSIONS.TASK_COMMENT_WRITE,
    PERMISSIONS.SPRINT_READ, PERMISSIONS.SPRINT_WRITE,
    PERMISSIONS.TIME_READ, PERMISSIONS.TIME_WRITE, PERMISSIONS.TIME_APPROVE,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.LEAVE_READ, PERMISSIONS.LEAVE_WRITE, PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.ASSET_READ, PERMISSIONS.ASSET_APPROVE,
    PERMISSIONS.BADGE_READ, PERMISSIONS.BADGE_AWARD,
    PERMISSIONS.PROFILE_READ, PERMISSIONS.PROFILE_WRITE,
    PERMISSIONS.ANNOUNCEMENT_READ,
    PERMISSIONS.ORG_READ,
  ],
  [ROLES.TEAM_MEMBER]: [
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.STANDUP_SUBMIT, PERMISSIONS.STANDUP_READ,
    PERMISSIONS.EOD_SUBMIT, PERMISSIONS.EOD_READ,
    PERMISSIONS.ACTION_READ, PERMISSIONS.ACTION_WRITE,
    PERMISSIONS.BLOCKER_READ, PERMISSIONS.BLOCKER_WRITE,
    PERMISSIONS.RAID_READ, PERMISSIONS.DECISION_READ,
    PERMISSIONS.MILESTONE_READ,
    PERMISSIONS.REPORT_READ, PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ, PERMISSIONS.TEAM_READ,
    PERMISSIONS.TASK_READ, PERMISSIONS.TASK_WRITE, PERMISSIONS.TASK_COMMENT_WRITE,
    PERMISSIONS.SPRINT_READ,
    PERMISSIONS.TIME_READ, PERMISSIONS.TIME_WRITE,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.LEAVE_READ, PERMISSIONS.LEAVE_WRITE,
    PERMISSIONS.ASSET_READ,
    PERMISSIONS.BADGE_READ,
    PERMISSIONS.PROFILE_READ, PERMISSIONS.PROFILE_WRITE,
    PERMISSIONS.ANNOUNCEMENT_READ,
    PERMISSIONS.ORG_READ,
  ],
  [ROLES.EXEC]: [
    PERMISSIONS.PROJECT_READ, PERMISSIONS.STANDUP_READ, PERMISSIONS.EOD_READ,
    PERMISSIONS.ACTION_READ, PERMISSIONS.BLOCKER_READ,
    PERMISSIONS.RAID_READ, PERMISSIONS.DECISION_READ, PERMISSIONS.MILESTONE_READ,
    PERMISSIONS.REPORT_READ, PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ, PERMISSIONS.TEAM_READ,
    PERMISSIONS.AI_READ, PERMISSIONS.AUDIT_READ,
    PERMISSIONS.TASK_READ, PERMISSIONS.SPRINT_READ,
    PERMISSIONS.TIME_READ, PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.LEAVE_READ,
    PERMISSIONS.ASSET_READ, PERMISSIONS.BADGE_READ, PERMISSIONS.PROFILE_READ,
    PERMISSIONS.ANNOUNCEMENT_READ, PERMISSIONS.ORG_READ,
  ],
  [ROLES.CLIENT]: [
    PERMISSIONS.PROJECT_READ, PERMISSIONS.MILESTONE_READ,
    PERMISSIONS.REPORT_READ, PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ,
  ],
});

// ─── Table Names — All 60 tables ──────────────────────────────────────────────
const TABLES = Object.freeze({
  // Existing
  TENANTS: 'tenants', USERS: 'users',
  PROJECTS: 'projects', PROJECT_MEMBERS: 'project_members',
  MILESTONES: 'milestones',
  STANDUP_ENTRIES: 'standup_entries', EOD_ENTRIES: 'eod_entries',
  ACTIONS: 'actions', BLOCKERS: 'blockers',
  RISKS: 'risks', ISSUES: 'issues', DEPENDENCIES: 'dependencies', ASSUMPTIONS: 'assumptions',
  DECISIONS: 'decisions', REPORTS: 'reports',
  AUDIT_LOGS: 'audit_logs', NOTIFICATION_EVENTS: 'notification_events',
  NOTIFICATIONS: 'notifications', TEAMS: 'teams', TEAM_MEMBERS: 'team_members',
  // Task & Sprint
  SPRINTS: 'sprints', TASKS: 'tasks',
  TASK_ATTACHMENTS: 'task_attachments', TASK_COMMENTS: 'task_comments',
  TASK_STATUS_HISTORY: 'task_status_history', SPRINT_MEMBERS: 'sprint_members',
 
  // Time Tracking
  TIME_ENTRIES: 'time_entries', TIME_APPROVAL_REQUESTS: 'time_approval_requests',
  TIME_EXPORT_JOBS: 'time_export_jobs',
  // People
  ATTENDANCE_RECORDS: 'attendance_records', ATTENDANCE_POLICIES: 'attendance_policies',
  LEAVE_TYPES: 'leave_types', LEAVE_BALANCES: 'leave_balances',
  LEAVE_REQUESTS: 'leave_requests', LEAVE_CALENDAR: 'leave_calendar',
  ANNOUNCEMENTS: 'announcements', ANNOUNCEMENT_READS: 'announcement_reads',
  // Assets
  ASSET_CATEGORIES: 'asset_categories', ASSETS: 'assets',
  ASSET_REQUESTS: 'asset_requests', ASSET_ASSIGNMENTS: 'asset_assignments',
  ASSET_MAINTENANCE: 'asset_maintenance',
  // Badges & Profile
  USER_PROFILES: 'user_profiles', BADGE_DEFINITIONS: 'badge_definitions',
  USER_BADGES: 'user_badges',
  // Config
  WORKFLOW_CONFIGS: 'workflow_configs', FORM_CONFIGS: 'form_configs',
  PERMISSION_OVERRIDES: 'permission_overrides', FEATURE_FLAGS: 'feature_flags',
  PROJECT_PERMISSIONS: 'project_permissions',
  NOTIFICATION_PREFERENCES: 'notification_preferences',
});

// ─── Status Enums ─────────────────────────────────────────────────────────────
const TASK_STATUS   = Object.freeze({ TODO: 'TODO', IN_PROGRESS: 'IN_PROGRESS', IN_REVIEW: 'IN_REVIEW', DONE: 'DONE', CANCELLED: 'CANCELLED' });
const TASK_TYPE     = Object.freeze({ TASK: 'TASK', STORY: 'STORY', BUG: 'BUG', SUBTASK: 'SUBTASK', EPIC: 'EPIC' });
const SPRINT_STATUS = Object.freeze({ PLANNING: 'PLANNING', ACTIVE: 'ACTIVE', COMPLETED: 'COMPLETED', CANCELLED: 'CANCELLED' });
const TIME_STATUS   = Object.freeze({ DRAFT: 'DRAFT', SUBMITTED: 'SUBMITTED', APPROVED: 'APPROVED', REJECTED: 'REJECTED' });
const LEAVE_STATUS  = Object.freeze({ PENDING: 'PENDING', APPROVED: 'APPROVED', REJECTED: 'REJECTED', CANCELLED: 'CANCELLED' });
const ASSET_STATUS  = Object.freeze({ AVAILABLE: 'AVAILABLE', ASSIGNED: 'ASSIGNED', MAINTENANCE: 'MAINTENANCE', RETIRED: 'RETIRED', LOST: 'LOST' });
const ASSET_REQ_STATUS = Object.freeze({ PENDING: 'PENDING', APPROVED: 'APPROVED', REJECTED: 'REJECTED', FULFILLED: 'FULFILLED', CANCELLED: 'CANCELLED' });
const ATTENDANCE_STATUS = Object.freeze({ PRESENT: 'PRESENT', ABSENT: 'ABSENT', WFH: 'WFH', LATE: 'LATE', HALF_DAY: 'HALF_DAY', HOLIDAY: 'HOLIDAY', ON_LEAVE: 'ON_LEAVE' });
const BADGE_LEVEL   = Object.freeze({ BRONZE: 'BRONZE', SILVER: 'SILVER', GOLD: 'GOLD', PLATINUM: 'PLATINUM' });
const BADGE_CATEGORY = Object.freeze({ PERFORMANCE: 'PERFORMANCE', COLLABORATION: 'COLLABORATION', INNOVATION: 'INNOVATION', LEADERSHIP: 'LEADERSHIP', SPECIAL: 'SPECIAL' });
const SEVERITY      = Object.freeze({ CRITICAL: 'CRITICAL', HIGH: 'HIGH', MEDIUM: 'MEDIUM', LOW: 'LOW' });
const USER_STATUS   = Object.freeze({ ACTIVE: 'ACTIVE', INACTIVE: 'INACTIVE', INVITED: 'INVITED' });
const RAG_STATUS    = Object.freeze({ RED: 'RED', AMBER: 'AMBER', GREEN: 'GREEN' });

// ─── Notification Types ───────────────────────────────────────────────────────
const NOTIFICATION_TYPE = Object.freeze({
  // Existing
  STANDUP_REMINDER: 'STANDUP_REMINDER', EOD_REMINDER: 'EOD_REMINDER',
  ACTION_OVERDUE: 'ACTION_OVERDUE', BLOCKER_ESCALATION: 'BLOCKER_ESCALATION',
  BLOCKER_ADDED: 'BLOCKER_ADDED', MEMBER_ADDED: 'MEMBER_ADDED',
  PROJECT_ASSIGNED: 'PROJECT_ASSIGNED', TEAM_UPDATED: 'TEAM_UPDATED',
  REPORT_READY: 'REPORT_READY', DAILY_SUMMARY: 'DAILY_SUMMARY', GENERAL: 'GENERAL',
  // New
  TASK_ASSIGNED: 'TASK_ASSIGNED', TASK_STATUS_CHANGED: 'TASK_STATUS_CHANGED',
  TASK_COMMENT_ADDED: 'TASK_COMMENT_ADDED', TASK_DUE_SOON: 'TASK_DUE_SOON', TASK_OVERDUE: 'TASK_OVERDUE',
  SPRINT_STARTED: 'SPRINT_STARTED', SPRINT_ENDING_SOON: 'SPRINT_ENDING_SOON', SPRINT_COMPLETED: 'SPRINT_COMPLETED',
  TIME_APPROVAL_NEEDED: 'TIME_APPROVAL_NEEDED', TIME_APPROVAL_REMINDER: 'TIME_APPROVAL_REMINDER',
  TIME_ENTRY_APPROVED: 'TIME_ENTRY_APPROVED', TIME_ENTRY_REJECTED: 'TIME_ENTRY_REJECTED',
  LEAVE_APPROVAL_NEEDED: 'LEAVE_APPROVAL_NEEDED', LEAVE_APPROVAL_REMINDER: 'LEAVE_APPROVAL_REMINDER',
  LEAVE_APPROVED: 'LEAVE_APPROVED', LEAVE_REJECTED: 'LEAVE_REJECTED',
  ATTENDANCE_ANOMALY: 'ATTENDANCE_ANOMALY', ATTENDANCE_LATE: 'ATTENDANCE_LATE',
  ASSET_REQUEST_RAISED: 'ASSET_REQUEST_RAISED', ASSET_REQUEST_APPROVED: 'ASSET_REQUEST_APPROVED',
  ASSET_REQUEST_REJECTED: 'ASSET_REQUEST_REJECTED', ASSET_ASSIGNED: 'ASSET_ASSIGNED',
  ASSET_MAINTENANCE_DUE: 'ASSET_MAINTENANCE_DUE',
  BADGE_AWARDED: 'BADGE_AWARDED', BADGE_REVOKED: 'BADGE_REVOKED',
  ANNOUNCEMENT_PUBLISHED: 'ANNOUNCEMENT_PUBLISHED',
  AI_SUMMARY_READY: 'AI_SUMMARY_READY', BURNOUT_ALERT: 'BURNOUT_ALERT',
});

const AUDIT_ACTION = Object.freeze({
  CREATE: 'CREATE', UPDATE: 'UPDATE', DELETE: 'DELETE',
  STATUS_CHANGE: 'STATUS_CHANGE', RAG_CHANGE: 'RAG_CHANGE',
  ROLE_CHANGE: 'ROLE_CHANGE', ESCALATE: 'ESCALATE',
  ASSIGN: 'ASSIGN', UNASSIGN: 'UNASSIGN',
  APPROVE: 'APPROVE', REJECT: 'REJECT',
  SUBMIT: 'SUBMIT', RETURN: 'RETURN',
  BULK_IMPORT: 'BULK_IMPORT',
  NOTIFY_SENT: 'NOTIFY_SENT', NOTIFY_FAILED: 'NOTIFY_FAILED', NOTIFY_SKIPPED: 'NOTIFY_SKIPPED',
});

const PROJECT_MEMBER_ROLES = Object.freeze([
  'DELIVERY_LEAD', 'PROJECT_MANAGER', 'SCRUM_MASTER', 'PRODUCT_OWNER',
  'TECH_LEAD', 'SENIOR_DEVELOPER', 'DEVELOPER', 'DEVOPS_ENGINEER',
  'TESTER', 'DESIGNER', 'BUSINESS_ANALYST', 'DATA_ANALYST',
  'STAKEHOLDER', 'OBSERVER', 'LEAD', 'MEMBER',
]);

module.exports = {
  ROLES, PERMISSIONS, ROLE_PERMISSIONS, TABLES,
  TASK_STATUS, TASK_TYPE, SPRINT_STATUS, TIME_STATUS,
  LEAVE_STATUS, ASSET_STATUS, ASSET_REQ_STATUS, ATTENDANCE_STATUS,
  BADGE_LEVEL, BADGE_CATEGORY, SEVERITY,
  USER_STATUS, RAG_STATUS,
  NOTIFICATION_TYPE, AUDIT_ACTION, PROJECT_MEMBER_ROLES,
};
