'use strict';
const express = require('express');
const router  = express.Router();
const RBACMiddleware   = require('../middleware/RBACMiddleware');
const BadgeController  = require('../controllers/BadgeController');
const { PERMISSIONS }  = require('../utils/Constants');
const asyncHandler = require('express-async-handler');
const ctrl = (req) => new BadgeController(req.catalystApp);
router.get('/leaderboard',           RBACMiddleware.require(PERMISSIONS.BADGE_READ),  asyncHandler((req, res) => ctrl(req).leaderboard(req, res)));
router.get('/',                      RBACMiddleware.require(PERMISSIONS.BADGE_READ),  asyncHandler((req, res) => ctrl(req).list(req, res)));
router.post('/',                     RBACMiddleware.require(PERMISSIONS.BADGE_WRITE), asyncHandler((req, res) => ctrl(req).create(req, res)));
router.put('/:badgeId',              RBACMiddleware.require(PERMISSIONS.BADGE_WRITE), asyncHandler((req, res) => ctrl(req).update(req, res)));
router.post('/:badgeId/award',       RBACMiddleware.require(PERMISSIONS.BADGE_AWARD), asyncHandler((req, res) => ctrl(req).award(req, res)));
router.delete('/user-badges/:awardId', RBACMiddleware.require(PERMISSIONS.BADGE_AWARD), asyncHandler((req, res) => ctrl(req).revoke(req, res)));
module.exports = router;
