'use strict';
const express = require('express');
const router  = express.Router();
const AuthMiddleware    = require('./middleware/AuthMiddleware');
const workflowRoutes   = require('./routes/workflowRoutes');
const formRoutes       = require('./routes/formRoutes');
const permissionRoutes = require('./routes/permissionRoutes');
const featureRoutes    = require('./routes/featureRoutes');
const migrationRoutes  = require('./routes/migrationRoutes');
const seedRoutes       = require('./routes/seedRoutes');
router.get('/health', (req, res) => res.json({ success: true, service: 'admin_config_service', ts: Date.now() }));
router.use(AuthMiddleware.authenticate);
router.use('/workflows',   workflowRoutes);
router.use('/forms',       formRoutes);
router.use('/permissions', permissionRoutes);
router.use('/features',    featureRoutes);
router.use('/migration',   migrationRoutes);
router.use('/seed',        seedRoutes);
module.exports = router;
