import type { UserRole } from '../types';

// Mirrors backend Constants.js PERMISSIONS exactly
export const PERMISSIONS = {
  PROJECT_READ:    'PROJECT_READ',
  PROJECT_WRITE:   'PROJECT_WRITE',
  STANDUP_SUBMIT:  'STANDUP_SUBMIT',
  STANDUP_READ:    'STANDUP_READ',
  EOD_SUBMIT:      'EOD_SUBMIT',
  EOD_READ:        'EOD_READ',
  ACTION_READ:     'ACTION_READ',
  ACTION_WRITE:    'ACTION_WRITE',
  BLOCKER_READ:    'BLOCKER_READ',
  BLOCKER_WRITE:   'BLOCKER_WRITE',
  RAID_READ:       'RAID_READ',
  RAID_WRITE:      'RAID_WRITE',
  DECISION_READ:   'DECISION_READ',
  DECISION_WRITE:  'DECISION_WRITE',
  MILESTONE_READ:  'MILESTONE_READ',
  MILESTONE_WRITE: 'MILESTONE_WRITE',
  REPORT_READ:     'REPORT_READ',
  REPORT_WRITE:    'REPORT_WRITE',
  DASHBOARD_READ:  'DASHBOARD_READ',
  ADMIN_USERS:        'ADMIN_USERS',
  ADMIN_SETTINGS:     'ADMIN_SETTINGS',
  INVITE_USER:        'INVITE_USER',
  NOTIFICATION_READ:  'NOTIFICATION_READ',
  TEAM_READ:          'TEAM_READ',
  TEAM_WRITE:         'TEAM_WRITE',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Mirrors backend Constants.js ROLE_PERMISSIONS exactly
const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  TENANT_ADMIN: Object.values(PERMISSIONS),
  DELIVERY_LEAD: [
    PERMISSIONS.PROJECT_READ, PERMISSIONS.PROJECT_WRITE,
    PERMISSIONS.STANDUP_SUBMIT, PERMISSIONS.STANDUP_READ,
    PERMISSIONS.EOD_SUBMIT, PERMISSIONS.EOD_READ,
    PERMISSIONS.ACTION_READ, PERMISSIONS.ACTION_WRITE,
    PERMISSIONS.BLOCKER_READ, PERMISSIONS.BLOCKER_WRITE,
    PERMISSIONS.RAID_READ, PERMISSIONS.RAID_WRITE,
    PERMISSIONS.DECISION_READ, PERMISSIONS.DECISION_WRITE,
    PERMISSIONS.MILESTONE_READ, PERMISSIONS.MILESTONE_WRITE,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_WRITE,
    PERMISSIONS.DASHBOARD_READ, PERMISSIONS.INVITE_USER,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.TEAM_READ, PERMISSIONS.TEAM_WRITE,
  ],
  TEAM_MEMBER: [
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.STANDUP_SUBMIT, PERMISSIONS.STANDUP_READ,
    PERMISSIONS.EOD_SUBMIT, PERMISSIONS.EOD_READ,
    PERMISSIONS.ACTION_READ, PERMISSIONS.ACTION_WRITE,
    PERMISSIONS.BLOCKER_READ, PERMISSIONS.BLOCKER_WRITE,
    PERMISSIONS.RAID_READ,
    PERMISSIONS.DECISION_READ,
    PERMISSIONS.MILESTONE_READ,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_WRITE,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.TEAM_READ,
  ],
  PMO: [
    PERMISSIONS.PROJECT_READ, PERMISSIONS.PROJECT_WRITE,
    PERMISSIONS.STANDUP_READ,
    PERMISSIONS.EOD_READ,
    PERMISSIONS.ACTION_READ, PERMISSIONS.ACTION_WRITE,
    PERMISSIONS.BLOCKER_READ, PERMISSIONS.BLOCKER_WRITE,
    PERMISSIONS.RAID_READ, PERMISSIONS.RAID_WRITE,
    PERMISSIONS.DECISION_READ, PERMISSIONS.DECISION_WRITE,
    PERMISSIONS.MILESTONE_READ, PERMISSIONS.MILESTONE_WRITE,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_WRITE,
    PERMISSIONS.DASHBOARD_READ, PERMISSIONS.INVITE_USER,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.TEAM_READ, PERMISSIONS.TEAM_WRITE,
  ],
  EXEC: [
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.STANDUP_READ,
    PERMISSIONS.EOD_READ,
    PERMISSIONS.ACTION_READ,
    PERMISSIONS.BLOCKER_READ,
    PERMISSIONS.RAID_READ,
    PERMISSIONS.DECISION_READ,
    PERMISSIONS.MILESTONE_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.TEAM_READ,
  ],
  CLIENT: [
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.MILESTONE_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ,
  ],
};

/** Returns true if the given role has the given permission. */
export const canDo = (role: UserRole | undefined | null, permission: Permission): boolean => {
  if (!role) return false;
  return (ROLE_PERMISSIONS[role] ?? []).includes(permission);
};

/** Returns which roles an inviter can invite. */
export const INVITE_ALLOWED_ROLES: Record<string, UserRole[]> = {
  TENANT_ADMIN:  ['TENANT_ADMIN', 'PMO', 'DELIVERY_LEAD', 'TEAM_MEMBER', 'EXEC', 'CLIENT'],
  PMO:           ['DELIVERY_LEAD', 'TEAM_MEMBER', 'EXEC', 'CLIENT'],
  DELIVERY_LEAD: ['TEAM_MEMBER', 'CLIENT'],
};
