'use strict';

// ─── User Roles ───────────────────────────────────────────────────────────────
const ROLES = Object.freeze({
  TENANT_ADMIN:   'TENANT_ADMIN',
  DELIVERY_LEAD:  'DELIVERY_LEAD',
  TEAM_MEMBER:    'TEAM_MEMBER',
  PMO:            'PMO',
  EXEC:           'EXEC',
  CLIENT:         'CLIENT',
});

// ─── Permissions ──────────────────────────────────────────────────────────────
const PERMISSIONS = Object.freeze({
  // Core
  PROJECT_READ: 'PROJECT_READ', PROJECT_WRITE: 'PROJECT_WRITE',
  STANDUP_SUBMIT: 'STANDUP_SUBMIT', STANDUP_READ: 'STANDUP_READ',
  EOD_SUBMIT: 'EOD_SUBMIT', EOD_READ: 'EOD_READ',
  ACTION_READ: 'ACTION_READ', ACTION_WRITE: 'ACTION_WRITE',
  BLOCKER_READ: 'BLOCKER_READ', BLOCKER_WRITE: 'BLOCKER_WRITE',
  RAID_READ: 'RAID_READ', RAID_WRITE: 'RAID_WRITE',
  DECISION_READ: 'DECISION_READ', DECISION_WRITE: 'DECISION_WRITE',
  MILESTONE_READ: 'MILESTONE_READ', MILESTONE_WRITE: 'MILESTONE_WRITE',
  REPORT_READ: 'REPORT_READ', REPORT_WRITE: 'REPORT_WRITE',
  DASHBOARD_READ: 'DASHBOARD_READ',
  ADMIN_USERS: 'ADMIN_USERS', ADMIN_SETTINGS: 'ADMIN_SETTINGS',
  INVITE_USER: 'INVITE_USER',
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  TEAM_READ: 'TEAM_READ', TEAM_WRITE: 'TEAM_WRITE',
  AI_READ: 'AI_READ', AUDIT_READ: 'AUDIT_READ',
  TASK_READ: 'TASK_READ', TASK_WRITE: 'TASK_WRITE',
  TASK_COMMENT_WRITE: 'TASK_COMMENT_WRITE',
  SPRINT_READ: 'SPRINT_READ', SPRINT_WRITE: 'SPRINT_WRITE',
  SPRINT_VIEW_ALL: 'SPRINT_VIEW_ALL',
  TIME_READ: 'TIME_READ', TIME_WRITE: 'TIME_WRITE', TIME_APPROVE: 'TIME_APPROVE',
  ATTENDANCE_READ: 'ATTENDANCE_READ', ATTENDANCE_WRITE: 'ATTENDANCE_WRITE', ATTENDANCE_ADMIN: 'ATTENDANCE_ADMIN',
  LEAVE_READ: 'LEAVE_READ', LEAVE_WRITE: 'LEAVE_WRITE', LEAVE_APPROVE: 'LEAVE_APPROVE', LEAVE_ADMIN: 'LEAVE_ADMIN',
  ASSET_READ: 'ASSET_READ', ASSET_WRITE: 'ASSET_WRITE',
  ASSET_ASSIGN: 'ASSET_ASSIGN', ASSET_APPROVE: 'ASSET_APPROVE', ASSET_ADMIN: 'ASSET_ADMIN',
  ASSET_SCAN_FULL: 'ASSET_SCAN_FULL', ASSET_SCAN_BASIC: 'ASSET_SCAN_BASIC',
  BADGE_READ: 'BADGE_READ', BADGE_WRITE: 'BADGE_WRITE', BADGE_AWARD: 'BADGE_AWARD',
  PROFILE_READ: 'PROFILE_READ', PROFILE_WRITE: 'PROFILE_WRITE',
  ANNOUNCEMENT_READ: 'ANNOUNCEMENT_READ', ANNOUNCEMENT_WRITE: 'ANNOUNCEMENT_WRITE',
  ORG_READ: 'ORG_READ', ORG_WRITE: 'ORG_WRITE',
  CONFIG_READ: 'CONFIG_READ', CONFIG_WRITE: 'CONFIG_WRITE',
  ORG_ROLE_READ: 'ORG_ROLE_READ', ORG_ROLE_WRITE: 'ORG_ROLE_WRITE',
  PROJECT_DATA_VIEW_ALL: 'PROJECT_DATA_VIEW_ALL',

  // ── Project Documentation (new) ───────────────────────────────────────────
  DOC_READ:   'DOC_READ',   // view docs & folders in assigned projects
  DOC_WRITE:  'DOC_WRITE',  // upload files, create folders, edit metadata
  DOC_DELETE: 'DOC_DELETE', // delete own docs/folders
  DOC_SHARE:  'DOC_SHARE',  // create / revoke public share links
  DOC_ADMIN:  'DOC_ADMIN',  // delete anyone's docs, manage all project docs
});

// ─── Role → Permission Matrix ─────────────────────────────────────────────────
const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.TENANT_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.PMO]: [
    PERMISSIONS.PROJECT_READ, PERMISSIONS.PROJECT_WRITE,
    PERMISSIONS.STANDUP_READ, PERMISSIONS.EOD_READ,
    PERMISSIONS.ACTION_READ, PERMISSIONS.ACTION_WRITE,
    PERMISSIONS.BLOCKER_READ, PERMISSIONS.BLOCKER_WRITE,
    PERMISSIONS.RAID_READ, PERMISSIONS.RAID_WRITE,
    PERMISSIONS.DECISION_READ, PERMISSIONS.DECISION_WRITE,
    PERMISSIONS.MILESTONE_READ, PERMISSIONS.MILESTONE_WRITE,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_WRITE,
    PERMISSIONS.DASHBOARD_READ, PERMISSIONS.INVITE_USER,
    PERMISSIONS.NOTIFICATION_READ, PERMISSIONS.TEAM_READ, PERMISSIONS.TEAM_WRITE,
    PERMISSIONS.AI_READ, PERMISSIONS.AUDIT_READ,
    PERMISSIONS.TASK_READ, PERMISSIONS.TASK_WRITE, PERMISSIONS.TASK_COMMENT_WRITE,
    PERMISSIONS.SPRINT_READ, PERMISSIONS.SPRINT_WRITE, PERMISSIONS.SPRINT_VIEW_ALL,
    PERMISSIONS.TIME_READ, PERMISSIONS.TIME_APPROVE,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_ADMIN,
    PERMISSIONS.LEAVE_READ, PERMISSIONS.LEAVE_APPROVE, PERMISSIONS.LEAVE_ADMIN,
    PERMISSIONS.ASSET_READ, PERMISSIONS.ASSET_ASSIGN, PERMISSIONS.ASSET_APPROVE,
    PERMISSIONS.BADGE_READ, PERMISSIONS.BADGE_WRITE, PERMISSIONS.BADGE_AWARD,
    PERMISSIONS.PROFILE_READ, PERMISSIONS.ANNOUNCEMENT_READ, PERMISSIONS.ANNOUNCEMENT_WRITE,
    PERMISSIONS.ORG_READ, PERMISSIONS.ORG_WRITE, PERMISSIONS.CONFIG_READ,
    PERMISSIONS.DOC_READ, PERMISSIONS.DOC_WRITE, PERMISSIONS.DOC_DELETE,
    PERMISSIONS.DOC_SHARE, PERMISSIONS.DOC_ADMIN,
  ],

  [ROLES.DELIVERY_LEAD]: [
    PERMISSIONS.PROJECT_READ, PERMISSIONS.PROJECT_WRITE,
    PERMISSIONS.STANDUP_SUBMIT, PERMISSIONS.STANDUP_READ,
    PERMISSIONS.EOD_SUBMIT, PERMISSIONS.EOD_READ,
    PERMISSIONS.ACTION_READ, PERMISSIONS.ACTION_WRITE,
    PERMISSIONS.BLOCKER_READ, PERMISSIONS.BLOCKER_WRITE,
    PERMISSIONS.RAID_READ, PERMISSIONS.RAID_WRITE,
    PERMISSIONS.DECISION_READ, PERMISSIONS.DECISION_WRITE,
    PERMISSIONS.MILESTONE_READ, PERMISSIONS.MILESTONE_WRITE,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_WRITE,
    PERMISSIONS.DASHBOARD_READ, PERMISSIONS.INVITE_USER,
    PERMISSIONS.NOTIFICATION_READ, PERMISSIONS.TEAM_READ, PERMISSIONS.TEAM_WRITE,
    PERMISSIONS.AI_READ,
    PERMISSIONS.TASK_READ, PERMISSIONS.TASK_WRITE, PERMISSIONS.TASK_COMMENT_WRITE,
    PERMISSIONS.SPRINT_READ, PERMISSIONS.SPRINT_WRITE, PERMISSIONS.SPRINT_VIEW_ALL,
    PERMISSIONS.TIME_READ, PERMISSIONS.TIME_WRITE, PERMISSIONS.TIME_APPROVE,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.LEAVE_READ, PERMISSIONS.LEAVE_WRITE, PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.ASSET_READ, PERMISSIONS.ASSET_APPROVE,
    PERMISSIONS.BADGE_READ, PERMISSIONS.BADGE_AWARD,
    PERMISSIONS.PROFILE_READ, PERMISSIONS.PROFILE_WRITE,
    PERMISSIONS.ANNOUNCEMENT_READ, PERMISSIONS.ORG_READ,
    PERMISSIONS.DOC_READ, PERMISSIONS.DOC_WRITE, PERMISSIONS.DOC_DELETE,
    PERMISSIONS.DOC_SHARE, PERMISSIONS.DOC_ADMIN,
  ],

  [ROLES.TEAM_MEMBER]: [
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.STANDUP_SUBMIT, PERMISSIONS.STANDUP_READ,
    PERMISSIONS.EOD_SUBMIT, PERMISSIONS.EOD_READ,
    PERMISSIONS.ACTION_READ, PERMISSIONS.ACTION_WRITE,
    PERMISSIONS.BLOCKER_READ, PERMISSIONS.BLOCKER_WRITE,
    PERMISSIONS.RAID_READ, PERMISSIONS.DECISION_READ,
    PERMISSIONS.MILESTONE_READ, PERMISSIONS.REPORT_READ, PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ, PERMISSIONS.TEAM_READ,
    PERMISSIONS.TASK_READ, PERMISSIONS.TASK_WRITE, PERMISSIONS.TASK_COMMENT_WRITE,
    PERMISSIONS.SPRINT_READ,
    PERMISSIONS.TIME_READ, PERMISSIONS.TIME_WRITE,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.LEAVE_READ, PERMISSIONS.LEAVE_WRITE,
    PERMISSIONS.ASSET_READ, PERMISSIONS.BADGE_READ,
    PERMISSIONS.PROFILE_READ, PERMISSIONS.PROFILE_WRITE,
    PERMISSIONS.ANNOUNCEMENT_READ, PERMISSIONS.ORG_READ,
    PERMISSIONS.DOC_READ, PERMISSIONS.DOC_WRITE, PERMISSIONS.DOC_DELETE, PERMISSIONS.DOC_SHARE,
  ],

  [ROLES.EXEC]: [
    PERMISSIONS.PROJECT_READ, PERMISSIONS.STANDUP_READ, PERMISSIONS.EOD_READ,
    PERMISSIONS.ACTION_READ, PERMISSIONS.BLOCKER_READ,
    PERMISSIONS.RAID_READ, PERMISSIONS.DECISION_READ, PERMISSIONS.MILESTONE_READ,
    PERMISSIONS.REPORT_READ, PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ, PERMISSIONS.TEAM_READ,
    PERMISSIONS.AI_READ, PERMISSIONS.AUDIT_READ,
    PERMISSIONS.TASK_READ, PERMISSIONS.SPRINT_READ,
    PERMISSIONS.TIME_READ, PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.LEAVE_READ,
    PERMISSIONS.ASSET_READ, PERMISSIONS.BADGE_READ, PERMISSIONS.PROFILE_READ,
    PERMISSIONS.ANNOUNCEMENT_READ, PERMISSIONS.ORG_READ,
    PERMISSIONS.DOC_READ,
  ],

  [ROLES.CLIENT]: [
    PERMISSIONS.PROJECT_READ, PERMISSIONS.MILESTONE_READ,
    PERMISSIONS.REPORT_READ, PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.DOC_READ,
  ],
});

// ─── Table Names ──────────────────────────────────────────────────────────────
const TABLES = Object.freeze({
  // Shared tables (read-only in this service)
  TENANTS: 'tenants', USERS: 'users',
  PROJECTS: 'projects', PROJECT_MEMBERS: 'project_members',
  AUDIT_LOGS: 'audit_logs', NOTIFICATIONS: 'notifications',
  USER_ORG_ROLES: 'user_org_roles', ORG_ROLES: 'org_roles',
  ORG_ROLE_PERMISSIONS: 'org_role_permissions', ORG_SHARING_RULES: 'org_sharing_rules',
  PERMISSION_OVERRIDES: 'permission_overrides',

  // Project Documentation (owned by this service)
  PROJECT_DOC_FOLDERS:  'project_doc_folders',
  PROJECT_DOCUMENTS:    'project_documents',
  PROJECT_DOC_VERSIONS: 'project_doc_versions',
  PROJECT_DOC_SHARES:   'project_doc_shares',
});

// ─── Status Enums ─────────────────────────────────────────────────────────────
const USER_STATUS  = Object.freeze({ ACTIVE: 'ACTIVE', INACTIVE: 'INACTIVE', INVITED: 'INVITED' });
const SHARE_TYPE   = Object.freeze({ DOCUMENT: 'DOCUMENT', FOLDER: 'FOLDER' });
const ACCESS_LEVEL = Object.freeze({ VIEW: 'VIEW', DOWNLOAD: 'DOWNLOAD', EDIT: 'EDIT' });
const LINK_TYPE    = Object.freeze({ PUBLIC: 'PUBLIC', MEMBERS: 'MEMBERS' });

const AUDIT_ACTION = Object.freeze({
  CREATE: 'CREATE', UPDATE: 'UPDATE', DELETE: 'DELETE',
  STATUS_CHANGE: 'STATUS_CHANGE', ASSIGN: 'ASSIGN',
});

module.exports = {
  ROLES, PERMISSIONS, ROLE_PERMISSIONS, TABLES,
  USER_STATUS, SHARE_TYPE, ACCESS_LEVEL, LINK_TYPE, AUDIT_ACTION,
};
